name: CI
on:
   push:
      branches:
         - main
   pull_request:
      branches:
         - main
   merge_group:
      types:
         - checks_requested

jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [14.x]
      steps:
         - name: Checkout Repository
           uses: actions/checkout@v3

         - name: Setup
           uses: ./.github/actions/setup

         - name: Prepare build
           run: yarn build

         - name: Deploy
           run: yarn deploy
           # env:
           #   user_name: 'github-actions[bot]'
           #   user_email: 'github-actions[bot]@users.noreply.github.com'
           #   repository: ${{ github.repository }}
           #   github_token: ${{ secrets.GITHUB_TOKEN }}
